////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE
////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
// BOARD_ESP32
#if defined(BOARD_ESP32)
  #include <HardwareSerial.h>

  HardwareSerial Serial2(2);
#endif

////////////////////////////////////////////////////////////////////////
// SYREN50 MOTOR CONTROLLER
#if defined(MOT_SYREN50)
  #include <Sabertooth.h>
  
  Sabertooth ST(128, Serial1); // Address 128, and use SWSerial as the serial port.

  // Throttle Values for Syren50
  const int throttleMin = -127;  // minimum or Reverse value
  const int throttleBrake = 0; // Brake value
  const int throttleMax = 127; // maximum or Forward value

  const int driverTimeout = 500; //Number of milliseconds before Sabertooth2x32 will stop motors.
  const int driverDeadband = 0; //Full deadband around throttleBrake -> If motor driver has deadband this amount will be removed
#endif

////////////////////////////////////////////////////////////////////////
// SABERTOOTH2x32 MOTOR CONTROLLER
#if defined(MOT_SABER2x32)
  #include <USBSabertooth.h>

  USBSabertoothSerial C(Serial1);
  USBSabertooth ST(C, 128);

  // Throttle values for Sabertooth2x32
  const int throttleMin = -2047;  // minimum or Reverse value
  const int throttleBrake = 0; // Brake value
  const int throttleMax = 2047; // maximum or Forward value
  
  const int driverTimeout = 500; //Number of milliseconds before Sabertooth2x32 will stop motors.
  const int driverDeadband = 0; //Full deadband around throttleBrake -> If motor driver has deadband this amount will be removed
#endif

////////////////////////////////////////////////////////////////////////
// SPARK MOTOR CONTROLLER
#if defined(MOT_SPARK)
  #if defined(BOARD_ESP32)
    #include <Servo.h>
    Servo motor1;
  #elif defined(BOARD_MAPLEMINI)
    #include <PWMServo.h>
    PWMServo motor1;
  #endif

  // Throttle values for Spark
  const int throttleMin = 0;  // minimum or Reverse value
  const int throttleBrake = 90; // Brake value
  const int throttleMax = 180; // maximum or Forward value

  const int driverDeadband = 23; //Full deadband around throttleBrake -> If motor driver has deadband this amount will be removed
#endif
////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////
// HTTP WEBSERVER
//#if defined(HTTP)
//  #include <WiFi.h>
//  #include <DNSServer.h>
//  
//  
//  const byte DNS_PORT = 53;
//  IPAddress apIP(192, 168, 1, 1);
//  DNSServer dnsServer;
//  WiFiServer server(80);
//  
//  String responseHTML = ""
//    "<!DOCTYPE html><html><head><title>CaptivePortal</title></head><body>"
//    "<h1>Hello World!</h1><p>This is a captive portal example. All requests will "
//    "be redirected here.</p></body></html>";
//
//#endif
